(part "STN3N40K3"
    (packageRef "SOT230P700X190-4N")
    (interface
        (port "1" (symbPinId 1) (portName "G") (portType INOUT))
        (port "2" (symbPinId 2) (portName "D_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "S") (portType INOUT))
        (port "4" (symbPinId 4) (portName "D_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "511-STN3N40K3")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/STN3N40K3?qs=fiYlMTh1qt%252Bj9zCjjMVqhQ%3D%3D")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "STN3N40K3")
    (property "Description" "N-channel 400 V, 3  typ., 1.8 A SuperMESH3 Power MOSFET in a SOT-223 package")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/stn3n40k3.pdf")
    (property "symbolName1" "STN3N40K3")
)
