(part "B22AP"
    (packageRef "B22AP")
    (interface
        (port "1" (symbPinId 1) (portName "NO_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "COM_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NC_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "NO_2") (portType INOUT))
        (port "5" (symbPinId 5) (portName "COM_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "NC_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Mouser_Part_Number" "633-B22AP")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/NKK-Switches/B22AP?qs=j%2Fw1qMK5FF4ADLD4OYx5DQ%3D%3D")
    (property "Manufacturer_Name" "NKK Switches")
    (property "Manufacturer_Part_Number" "B22AP")
    (property "Description" "Toggle Switches DPDT ON-NONE-ON .394 BAT STRAIGHT PC")
    (property "Datasheet_Link" "https://www.digikey.ph/en/products/detail/nkk-switches/B22AP/379102?srsltid=AfmBOoq2ffh3TUAnDNiZJlaVxYCDEPLtTEJlIOaBAa2Y6mNiDAISLYZb")
    (property "symbolName1" "B22AP")
)
