(part "OPA4192IPWR"
    (packageRef "SOP65P640X120-14N")
    (interface
        (port "1" (symbPinId 1) (portName "OUT_A") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-IN_A") (portType INOUT))
        (port "3" (symbPinId 3) (portName "+_IN_A") (portType INOUT))
        (port "4" (symbPinId 4) (portName "V+") (portType INOUT))
        (port "5" (symbPinId 5) (portName "+_IN_B") (portType INOUT))
        (port "6" (symbPinId 6) (portName "-_IN_B") (portType INOUT))
        (port "7" (symbPinId 7) (portName "OUT_B") (portType INOUT))
        (port "8" (symbPinId 8) (portName "OUT_C") (portType INOUT))
        (port "9" (symbPinId 9) (portName "-_IN_C") (portType INOUT))
        (port "10" (symbPinId 10) (portName "+IN_C") (portType INOUT))
        (port "11" (symbPinId 11) (portName "V-") (portType INOUT))
        (port "12" (symbPinId 12) (portName "+_IN_D") (portType INOUT))
        (port "13" (symbPinId 13) (portName "-_IN_D") (portType INOUT))
        (port "14" (symbPinId 14) (portName "OUT_D") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-OPA4192IPWR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/OPA4192IPWR?qs=VymPLiRQZIQME3r0jgSK9g%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "OPA4192IPWR")
    (property "Description" "Low-Noise, Low Quiescent Current, 36V RRI/O Precision Op Amps, E-Trim Series")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/OPA4192")
    (property "symbolName1" "OPA4192IPWR")
)
