(part "LM7705MM_NOPB"
    (packageRef "SOP65P490X110-8N")
    (interface
        (port "1" (symbPinId 1) (portName "CF+") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VSS_1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "SD") (portType INOUT))
        (port "4" (symbPinId 4) (portName "VDD") (portType INOUT))
        (port "5" (symbPinId 5) (portName "VSS_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "VOUT") (portType INOUT))
        (port "7" (symbPinId 7) (portName "CRES") (portType INOUT))
        (port "8" (symbPinId 8) (portName "CF-") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "926-LM7705MM/NOPB")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/LM7705MM-NOPB?qs=QbsRYf82W3EUoG7CCLtS5A%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "LM7705MM/NOPB")
    (property "Description" "Low Noise Negative Bias Generator")
    (property "Datasheet_Link" "http://www.ti.com/lit/gpn/LM7705")
    (property "symbolName1" "LM7705MM_NOPB")
)
