(part "OPA462IDDAR"
    (packageRef "SOIC127P600X170-9N")
    (interface
        (port "1" (symbPinId 1) (portName "E/D_COM") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-IN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "+IN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "V-") (portType INOUT))
        (port "5" (symbPinId 5) (portName "STATUS_FLAG") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUT") (portType INOUT))
        (port "7" (symbPinId 7) (portName "V+") (portType INOUT))
        (port "8" (symbPinId 8) (portName "E/D") (portType INOUT))
        (port "9" (symbPinId 9) (portName "EP") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-OPA462IDDAR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/OPA462IDDAR?qs=9r4v7xj2Lnl6T1pF18R4kw%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "OPA462IDDAR")
    (property "Description" "High-Voltage, High-Current (30-mA) Operational Amplifier")
    (property "Datasheet_Link" "https://www.ti.com/lit/gpn/OPA462")
    (property "symbolName1" "OPA462IDDAR")
)
