(part "1757268"
    (packageRef "1757268")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "651-1757268")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Phoenix-Contact/1757268?qs=uD%2FdkN7XIa2BicmSj3mD7g%3D%3D")
    (property "Manufacturer_Name" "Phoenix Contact")
    (property "Manufacturer_Part_Number" "1757268")
    (property "Description" "MSTBA 2,5/ 4-G-5,08 - PCB headers, nominal cross section: 2.5 mm<sup>2</sup>, color: green, nominal current: 12 A, rated voltage (III/2): 320 V, contact surface: Sn, contact connection type: Pin, number of potentials: 4, number of rows: 1, number of positions: 4, number of connections: 4, product range: MSTBA 2,5/..-G, pitch: 5.08 mm, mounting: Wave soldering, pin layout: Linear pinning, solder pin [P]: 3.23 mm, number of solder pins per potential: 1, plug-in system: COMBICON MSTB 2,5, Pin connector pattern")
    (property "Datasheet_Link" "https://www.phoenixcontact.com/en-us/products/pcb-header-mstba-25-4-g-508-1757268?type=pdf")
    (property "symbolName1" "1757268")
)
