(part "TPS259474LRPWR"
    (packageRef "TPS259474LRPWR")
    (interface
        (port "1" (symbPinId 1) (portName "EN/UVLO_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "OVLO/_OVCSEL") (portType INOUT))
        (port "3" (symbPinId 3) (portName "PG/_AUXOFF") (portType INOUT))
        (port "4" (symbPinId 4) (portName "PGTH/%FLT_1%") (portType INOUT))
        (port "5" (symbPinId 5) (portName "IN") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUT") (portType INOUT))
        (port "7" (symbPinId 7) (portName "DVDT_1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "GND") (portType INOUT))
        (port "9" (symbPinId 9) (portName "ILM") (portType INOUT))
        (port "10" (symbPinId 10) (portName "ITIMER_1") (portType INOUT))
        (port "11" (symbPinId 11) (portName "EN/UVLO_2") (portType INOUT))
        (port "12" (symbPinId 12) (portName "PGTH/%FLT_2%") (portType INOUT))
        (port "13" (symbPinId 13) (portName "DVDT_2") (portType INOUT))
        (port "14" (symbPinId 14) (portName "ITIMER_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TPS259474LRPWR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS259474LRPWR?qs=iLbezkQI%252BsixXidX03eIQA%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS259474LRPWR")
    (property "Description" "Hot Swap Voltage Controllers 2.7-V to 23-V, 28-m?, 5.5-A eFuse with integrated reverse polarity protection")
    (property "Datasheet_Link" "https://www.ti.com/lit/gpn/tps25981")
    (property "symbolName1" "TPS259474LRPWR")
)
