(part "ECW-F2475JA"
    (packageRef "ECWF2475JA")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "667-ECW-F2475JA")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Panasonic/ECW-F2475JA?qs=GoZnPdyRfjbTFkwsw7ZE%252Bg%3D%3D")
    (property "Manufacturer_Name" "Panasonic")
    (property "Manufacturer_Part_Number" "ECW-F2475JA")
    (property "Description" "Film Capacitors 4.7uF 250VDC 5% MPP L/S=20mm")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/ECW-F2475JA.pdf")
    (property "symbolName1" "ECW-F2475JA")
)
