(part "DAC80501ZDGSR"
    (packageRef "SOP50P490X110-10N")
    (interface
        (port "1" (symbPinId 1) (portName "VDD") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VOUT") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NC_1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "AGND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "SPI2C") (portType INOUT))
        (port "6" (symbPinId 6) (portName "SCLK/SCL") (portType INOUT))
        (port "7" (symbPinId 7) (portName "%SYNC%/A0") (portType INOUT))
        (port "8" (symbPinId 8) (portName "SDIN/SDA") (portType INOUT))
        (port "9" (symbPinId 9) (portName "NC_2") (portType INOUT))
        (port "10" (symbPinId 10) (portName "VREFIO") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-DAC80501ZDGSR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/DAC80501ZDGSR?qs=%252B6g0mu59x7KTwAqkifaR1Q%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "DAC80501ZDGSR")
    (property "Description" "Digital to Analog Converters - DAC True 16-bit, 1-ch, SPI/I2C, voltage-output DAC in WSON package with precision internal reference 10-VSSOP -40 to 125")
    (property "Datasheet_Link" "https://www.ti.com/lit/ds/symlink/dac80501.pdf?ts=1622793671136&ref_url=https%253A%252F%252Fwww.ti.com%252Fstore%252Fti%252Fen%252Fp%252Fproduct%252F%253Fp%253DDAC80501ZDGSR")
    (property "symbolName1" "DAC80501ZDGSR")
)
