(part "LT8618EDDB_TRPBF"
    (packageRef "SON50P200X300X80-11N-D")
    (interface
        (port "1" (symbPinId 1) (portName "BST") (portType INOUT))
        (port "2" (symbPinId 2) (portName "SW") (portType INOUT))
        (port "3" (symbPinId 3) (portName "BIAS") (portType INOUT))
        (port "4" (symbPinId 4) (portName "INTVCC") (portType INOUT))
        (port "5" (symbPinId 5) (portName "RT") (portType INOUT))
        (port "6" (symbPinId 6) (portName "FB") (portType INOUT))
        (port "7" (symbPinId 7) (portName "TR/SS") (portType INOUT))
        (port "8" (symbPinId 8) (portName "PG") (portType INOUT))
        (port "9" (symbPinId 9) (portName "EN/UV") (portType INOUT))
        (port "10" (symbPinId 10) (portName "VIN") (portType INOUT))
        (port "11" (symbPinId 11) (portName "GND") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "584-LT8618EDDB#TRPBF")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices/LT8618EDDBTRPBF?qs=hWgE7mdIu5Ro6jCGwTYWww%3D%3D")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "LT8618EDDB#TRPBF")
    (property "Description" "Switching Voltage Regulators High Efficiency 60V/100mA Synchronous Bu")
    (property "Datasheet_Link" "https://www.mouser.ch/datasheet/2/609/lt8618_8618_3_3-1893268.pdf")
    (property "symbolName1" "LT8618EDDB_TRPBF")
)
