(part "5019"
    (packageRef "5019")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "220")
    (property "Mouser_Part_Number" "534-5019")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Keystone-Electronics/5019?qs=wOxb8XianXjjCAsb90Ilzw%3D%3D")
    (property "Manufacturer_Name" "Keystone Electronics")
    (property "Manufacturer_Part_Number" "5019")
    (property "Description" "Circuit Board Hardware - PCB TEST POINT")
    (property "Datasheet_Link" "https://www.keyelco.com/product-pdf.cfm?p=1357")
    (property "symbolName1" "5019")
)
