(part "ADP7142ARDZ-R7"
    (packageRef "SOIC127P600X175-9N")
    (interface
        (port "1" (symbPinId 1) (portName "VOUT_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VOUT_2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "SENSE/ADJ") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND_1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "EN") (portType INOUT))
        (port "6" (symbPinId 6) (portName "SS") (portType INOUT))
        (port "7" (symbPinId 7) (portName "VIN_1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VIN_2") (portType INOUT))
        (port "9" (symbPinId 9) (portName "GND_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "584-ADP7142ARDZ-R7")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices/ADP7142ARDZ-R7?qs=hpwIUhX6lWzjrObMcOmL6g%3D%3D")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "ADP7142ARDZ-R7")
    (property "Description" "40 V, 200 mA, Low Noise, CMOS LDO Linear Regulator")
    (property "Datasheet_Link" "https://www.analog.com/ADP7142/datasheet")
    (property "symbolName1" "ADP7142ARDZ-R7")
)
