(part "1803374"
    (packageRef "1803374")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "9" (symbPinId 9) (portName "9") (portType INOUT))
        (port "10" (symbPinId 10) (portName "10") (portType INOUT))
        (port "11" (symbPinId 11) (portName "11") (portType INOUT))
        (port "12" (symbPinId 12) (portName "12") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "651-1803374")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Phoenix-Contact/1803374?qs=%2FbRkJSLTVS9mX%2FTOf8pTQA%3D%3D")
    (property "Manufacturer_Name" "Phoenix Contact")
    (property "Manufacturer_Part_Number" "1803374")
    (property "Description" "MC 1,5/12-G-3,81 - PCB headers, nominal cross section: 1.5 mm<sup>2</sup>, color: green, nominal current: 8 A, rated voltage (III/2): 160 V, contact surface: Sn, contact connection type: Pin, number of potentials: 12, number of rows: 1, number of positions: 12, number of connections: 12, product range: MC 1,5/..-G, pitch: 3.81 mm, screw head form: L Slotted, mounting: Wave soldering, pin layout: Linear pinning, solder pin [P]: 3.4 mm, number of solder pins per potential: 1, plug-in system: COMBICON MC 1,5, ")
    (property "Datasheet_Link" "https://www.phoenixcontact.com/en-us/products/pcb-header-mc-1512-g-381-1803374?type=pdf")
    (property "symbolName1" "1803374")
)
