(part "TPS259472ARPWR"
    (packageRef "TPS259472ARPWR")
    (interface
        (port "1" (symbPinId 1) (portName "EN/UVLO_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "OVCSEL") (portType INOUT))
        (port "3" (symbPinId 3) (portName "PG") (portType INOUT))
        (port "4" (symbPinId 4) (portName "PGTH_1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "IN") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUT") (portType INOUT))
        (port "7" (symbPinId 7) (portName "DVDT_1") (portType INOUT))
        (port "8" (symbPinId 8) (portName "GND") (portType INOUT))
        (port "9" (symbPinId 9) (portName "ILM") (portType INOUT))
        (port "10" (symbPinId 10) (portName "ITIMER_1") (portType INOUT))
        (port "11" (symbPinId 11) (portName "ITIMER_2") (portType INOUT))
        (port "12" (symbPinId 12) (portName "EN/UVLO_2") (portType INOUT))
        (port "13" (symbPinId 13) (portName "PGTH_2") (portType INOUT))
        (port "14" (symbPinId 14) (portName "DVDT_2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TPS259472ARPWR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TPS259472ARPWR?qs=iLbezkQI%252BshCnrYg81AACA%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TPS259472ARPWR")
    (property "Description" "Hot Swap Voltage Controllers 2.7-V to 23-V, 28-m?, 5.5-A eFuse with integrated reverse polarity protection")
    (property "Datasheet_Link" "https://www.ti.com/lit/ds/symlink/tps25947.pdf?ts=1761904658681&ref_url=https%253A%252F%252Fwww.mouser.tw%252F")
    (property "symbolName1" "TPS259472ARPWR")
)
