(part "TSW-102-07-G-S"
    (packageRef "TSW-102-XX-YY-S")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "200-TSW10207GS")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Samtec/TSW-102-07-G-S?qs=iT52DjcXudsNPhlNCDp8vw%3D%3D")
    (property "Manufacturer_Name" "SAMTEC")
    (property "Manufacturer_Part_Number" "TSW-102-07-G-S")
    (property "Description" "2 Position, Single Row, Classic PCB Header Strips, 0.100&quot; pitch")
    (property "Datasheet_Link" "http://suddendocs.samtec.com/prints/tsw-xxx-xx-xxx-x-xx-xxx-mkt.pdf")
    (property "symbolName1" "TSW-102-07-G-S")
)
