(part "TSS-106-01-L-D"
    (packageRef "TSS-106-XX-YYY-D")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
        (port "7" (symbPinId 7) (portName "7") (portType INOUT))
        (port "8" (symbPinId 8) (portName "8") (portType INOUT))
        (port "9" (symbPinId 9) (portName "9") (portType INOUT))
        (port "10" (symbPinId 10) (portName "10") (portType INOUT))
        (port "11" (symbPinId 11) (portName "11") (portType INOUT))
        (port "12" (symbPinId 12) (portName "12") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "200-TSS10601LD")
    (property "Mouser_Price/Stock" "https://www.mouser.com/Search/Refine.aspx?Keyword=200-TSS10601LD")
    (property "Manufacturer_Name" "SAMTEC")
    (property "Manufacturer_Part_Number" "TSS-106-01-L-D")
    (property "Description" ".100" Shrouded Terminal Strip")
    (property "Datasheet_Link" "https://componentsearchengine.com/Datasheets/1/TSS-106-01-L-D.pdf")
    (property "symbolName1" "TSS-106-01-L-D")
)
