(part "0452003_MRL"
    (packageRef "FUSC6127X294N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "221")
    (property "Mouser_Part_Number" "576-0452003.MRL")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Littelfuse/0452003.MRL?qs=LpXnx4WbYtASasaWrk%2F1Ow%3D%3D")
    (property "Manufacturer_Name" "LITTELFUSE")
    (property "Manufacturer_Part_Number" "0452003.MRL")
    (property "Description" "Fuse SMD NANO2 Slo-Blo 3A T Littelfuse 3A T Surface Mount Fuse, 125 V ac/dc")
    (property "Datasheet_Link" "http://www.littelfuse.com/~/media/electronics/datasheets/fuses/littelfuse_fuse_452_454_datasheet.pdf.pdf")
    (property "symbolName1" "0452003_MRL")
)
