(part "STTH1R04A"
    (packageRef "DIOM5126X265N")
    (interface
        (port "1" (symbPinId 1) (portName "K") (portType INOUT))
        (port "2" (symbPinId 2) (portName "A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "122")
    (property "Mouser_Part_Number" "511-STTH1R04A")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/STMicroelectronics/STTH1R04A?qs=%252BB84zevwoRDGXZQYojB4Uw%3D%3D")
    (property "Manufacturer_Name" "STMicroelectronics")
    (property "Manufacturer_Part_Number" "STTH1R04A")
    (property "Description" "Rectifiers Ultrafast recovery Diode 1 A - 400 V")
    (property "Datasheet_Link" "https://www.st.com/resource/en/datasheet/stth1r04.pdf")
    (property "symbolName1" "STTH1R04A")
)
